name: Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC2148
